### ISSUE TITLE
Outreach is not centred.

### ISSUE THREAD

**Issue by kira0204** [sahil3Vedi/IEEE-VIT-#3]
The text `#Outreach` is not centered. You need to use a proper offset here if you are planning to use `col-lg-9`
https://github.com/sahil3Vedi/IEEE-VIT-/blob/cafeadf6b86b5d7e02357a92014b43d560c4f5c5/index.html#L433

**Comment by sahil3Vedi** [comment]
Offset has been removed. #outreach is now centred
