### ISSUE TITLE
Counterup

### ISSUE THREAD

**Issue by goelashwin36** [sahil3Vedi/IEEE-VIT-#7]
The counterup keeps on changing when viewed multiple times.

**Comment by kira0204** [comment]
Hey,
A better way to describe the issue would be appreciated

**Comment by sahil3Vedi** [comment]
Counter has been temporarily replaced with a static number.

**Comment by goelashwin36** [comment]
So when the Enigma section is viewed again and again by scrolling up and down then the value of counters keep on changing(decreasing).

**Comment by kira0204** [comment]
Let's reopen this until a proper fix has been implemented.
